[".local/share/leanplan"]
    type = "git-repo"
    url = "https://github.com/mynghn/leanplan.git"
    refreshPeriod = "168h"

[".local/share/leanplan.clone"]
    args = ["--depth=1"]

[".local/share/leanplan.pull"]
    args = ["--ff-only"]
