#!/bin/bash
# Provision the local recall-search query lane: exact (rg) + code (ck) + prose (qmd).
#
# Every network fetch belongs to this script. The query lane that agents use must
# work offline from its first query, so models are pulled here rather than lazily.
#
# qmd is vendored, not installed globally: its launcher re-execs `node` resolved
# from PATH (bun only when no node exists at all), and its native SQLite is
# ABI-locked to the installing node. A default global install therefore both
# lands a competing bin on PATH and breaks under whatever node the shell happens
# to resolve. Installing under a private prefix and exposing one PATH-pinning
# wrapper makes the node floor a private dependency of qmd instead of a standing
# requirement on this machine's node.
set -euo pipefail

QMD_VERSION="2.5.3"
CK_VERSION="0.7.11"
NODE_FORMULA="node@22"

BIN_DIR="$HOME/.local/bin"
QMD_PREFIX="$HOME/.local/share/local-recall/qmd-runtime"
QMD_WRAPPER="$BIN_DIR/qmd"
QMD_MODEL_CACHE="$HOME/.cache/qmd/models"
CK_MODEL_CACHE="$HOME/.cache/ck"
WARMUP_INDEX="local-recall-warmup"

# The prose corpora worth recalling by meaning: distilled knowledge, agent
# instructions, and managed planning docs. ~/.claude/skills is deliberately
# absent — it is mostly symlinks into the agent skills tree and would index the
# same files twice.
QMD_COLLECTIONS=(
  "kb-vault:$HOME/.local/share/metacognition-vault"
  "agent-skills:$HOME/.agents/skills"
  "chezmoi-docs:$HOME/.local/share/chezmoi/docs"
)

log() { printf 'local-recall: %s\n' "$1" >&2; }

# Homebrew is the one prerequisite treated as the platform floor. Skipping
# quietly would hand back a machine that silently lacks the capability, which is
# the portability guarantee this script exists to keep.
require_brew() {
  if ! command -v brew >/dev/null 2>&1; then
    cat >&2 <<'EOF'
local-recall: Homebrew is required to provision the recall-search engines.
local-recall: install it from https://brew.sh and re-run `chezmoi apply`.
EOF
    exit 1
  fi
}

ensure_formula() {
  local formula="$1"
  if brew list --formula "$formula" >/dev/null 2>&1; then
    return 0
  fi
  log "installing $formula"
  brew install "$formula"
}

# qmd's install and its invocation must agree on one node: the native SQLite
# addon is built for the installing node's ABI and fails to load under another.
node_bin_dir() {
  printf '%s/bin' "$(brew --prefix "$NODE_FORMULA")"
}

installed_qmd_version() {
  local pkg="$QMD_PREFIX/lib/node_modules/@tobilu/qmd/package.json"
  [ -f "$pkg" ] || return 1
  "$(node_bin_dir)/node" -p "require('$pkg').version" 2>/dev/null
}

ensure_qmd() {
  if [ "$(installed_qmd_version || true)" = "$QMD_VERSION" ]; then
    return 0
  fi
  log "installing qmd $QMD_VERSION into $QMD_PREFIX"
  PATH="$(node_bin_dir):$PATH" npm install -g --prefix "$QMD_PREFIX" \
    "@tobilu/qmd@$QMD_VERSION" >/dev/null
}

# A qmd anywhere on PATH outranks or is outranked by the wrapper purely by PATH
# order, which varies per machine. Removing them is what leaves the wrapper
# unambiguous rather than merely competitive.
remove_competing_qmd() {
  local found
  while IFS= read -r found; do
    [ -n "$found" ] || continue
    [ "$found" = "$QMD_WRAPPER" ] && continue
    log "removing competing qmd on PATH: $found"
    rm -f "$found"
  done < <(type -a -p qmd 2>/dev/null || true)
}

wrapper_content() {
  cat <<EOF
#!/bin/sh
# Generated by run_after_local-recall.sh — do not edit.
# Pins qmd's interpreter: its launcher re-execs node resolved from PATH, so an
# absolute node path would be discarded. Setting PATH is the mechanism.
PATH="$(node_bin_dir):\$PATH"
exec "$QMD_PREFIX/bin/qmd" "\$@"
EOF
}

ensure_wrapper() {
  if [ -f "$QMD_WRAPPER" ] && wrapper_content | cmp -s - "$QMD_WRAPPER"; then
    return 0
  fi
  log "writing qmd wrapper to $QMD_WRAPPER"
  mkdir -p "$BIN_DIR"
  wrapper_content > "$QMD_WRAPPER"
  chmod +x "$QMD_WRAPPER"
}

ensure_ck() {
  # cargo's default root (~/.cargo/bin) is not on PATH here; --root puts the
  # binary alongside the wrapper in a directory that is.
  if [ "$("$BIN_DIR/ck" --version 2>/dev/null | awk '{print $2}')" = "$CK_VERSION" ]; then
    return 0
  fi
  log "installing ck $CK_VERSION"
  cargo install ck-search --version "$CK_VERSION" --root "$HOME/.local" --quiet
}

# Neither engine exposes a model-pull command, so a real invocation against a
# throwaway corpus is the only way to force the download at provision time.
warm_ck() {
  if [ -d "$CK_MODEL_CACHE" ] && [ -n "$(ls -A "$CK_MODEL_CACHE" 2>/dev/null)" ]; then
    return 0
  fi
  local tmp
  tmp="$(mktemp -d)"
  trap 'rm -rf "$tmp"' RETURN
  printf 'fn placeholder() {}\n' > "$tmp/warmup.rs"
  log "pre-pulling ck embedding model (first run only)"
  "$BIN_DIR/ck" --sem "warm up the embedding model" "$tmp" >/dev/null 2>&1 || true
}

warm_qmd() {
  if [ -d "$QMD_MODEL_CACHE" ] && [ -n "$(ls -A "$QMD_MODEL_CACHE" 2>/dev/null)" ]; then
    return 0
  fi
  local tmp
  tmp="$(mktemp -d)"
  trap 'rm -rf "$tmp"' RETURN
  printf '# Warm Up\n\nText that exists only to make the engine load its models.\n' \
    > "$tmp/warmup.md"

  # A named index keeps the throwaway corpus out of the collections the skill
  # queries; embed pulls the embedding model, query pulls expansion + reranker.
  log "pre-pulling qmd models (first run only; ~2GB)"
  "$QMD_WRAPPER" --index "$WARMUP_INDEX" collection add "$tmp" >/dev/null 2>&1 || true
  "$QMD_WRAPPER" --index "$WARMUP_INDEX" embed >/dev/null 2>&1 || true
  "$QMD_WRAPPER" --index "$WARMUP_INDEX" query "what is this text for" >/dev/null 2>&1 || true
  rm -f "$HOME/.cache/qmd/$WARMUP_INDEX.sqlite"
}

# Registration is the one-time build; keeping results fresh afterwards is the
# search skill's job, which re-indexes incrementally before each query.
ensure_collections() {
  local entry name path added=0
  for entry in "${QMD_COLLECTIONS[@]}"; do
    name="${entry%%:*}"
    path="${entry#*:}"
    if [ ! -d "$path" ]; then
      log "corpus absent, not registering '$name': $path"
      continue
    fi
    if "$QMD_WRAPPER" collection list 2>/dev/null | grep -qF "$name"; then
      continue
    fi
    log "registering collection '$name' -> $path"
    "$QMD_WRAPPER" collection add "$path" --name "$name" >/dev/null
    added=1
  done

  # Registering indexes text but leaves vectors unbuilt, so a collection added
  # here cannot answer a meaning query until this runs.
  if [ "$added" -eq 1 ]; then
    log "building embeddings for newly registered collections"
    "$QMD_WRAPPER" embed >/dev/null
  fi
}

require_brew
ensure_formula "$NODE_FORMULA"
ensure_formula rust
ensure_formula ripgrep
ensure_qmd
ensure_wrapper
remove_competing_qmd
ensure_ck
warm_ck
warm_qmd
ensure_collections
